baseURL = "http://dagen.net"
languageCode = "en-us"
title = "Damon Gentry"
theme = "resume"
copyright = ""
summaryLength = "70"

[params]
    firstName = "Damon"
    lastName = "Gentry"
    address = "Beaverton, OR"
    contactNote = "DevOps Ninja" #used in QR code only
    profileImage = "static/img/damon_avatar.png"
    email = "damon@dagen.net"
    description = "DevOps leader with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    # gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"



